name: Issues

on: [issues]

jobs:
  update:
    name: Update Issue
    uses: bencekov/grafana-k8s-operator/.github/workflows/issues.yaml@main
    secrets: inherit
    with:
      component: observability
